// Country.ts

export interface CountryProps {
    name: string;
    officialName?: string;
    slug: string;
  
    // Codes internationaux
    iso2: string;
    iso3: string;
    numericCode: string;
    countryCode: string; // phone code
  
    // Monnaie
    currencyCode: string;
    currencyName: string;
    currencySymbol: string;
  
    // Formatage
    minLengthPhone: number;
    maxLengthPhone: number;
    phoneFormat?: string;
    postalCodeFormat?: string;
    usesPostalCode: boolean;
  }
  
  export class Country {
    name: string;
    officialName?: string;
    slug: string;
  
    iso2: string;
    iso3: string;
    numericCode: string;
    countryCode: string;
  
    currencyCode: string;
    currencyName: string;
    currencySymbol: string;
  
    minLengthPhone: number;
    maxLengthPhone: number;
    phoneFormat?: string;
    postalCodeFormat?: string;
    usesPostalCode: boolean;
  
    constructor(props: CountryProps) {
      this.name = props.name;
      this.officialName = props.officialName;
      this.slug = props.slug;
      this.iso2 = props.iso2;
      this.iso3 = props.iso3;
      this.numericCode = props.numericCode;
      this.countryCode = props.countryCode;
      this.currencyCode = props.currencyCode;
      this.currencyName = props.currencyName;
      this.currencySymbol = props.currencySymbol;
      this.minLengthPhone = props.minLengthPhone;
      this.maxLengthPhone = props.maxLengthPhone;
      this.phoneFormat = props.phoneFormat;
      this.postalCodeFormat = props.postalCodeFormat;
      this.usesPostalCode = props.usesPostalCode;
    }
  
    // Constructeur depuis JSON
    static fromJson(json: any): Country {
      return new Country({
        name: json["name"],
        officialName: json["official_name"],
        slug: json["slug"],
        iso2: json["iso2"],
        iso3: json["iso3"],
        numericCode: json["numeric_code"],
        countryCode: json["country_code"],
        currencyCode: json["currency_code"],
        currencyName: json["currency_name"],
        currencySymbol: json["currency_symbol"],
        minLengthPhone: json["min_length_phone"],
        maxLengthPhone: json["max_length_phone"],
        phoneFormat: json["phone_format"],
        postalCodeFormat: json["postal_code_format"],
        usesPostalCode: json["uses_postal_code"],
      });
    }
  
    // Conversion vers JSON
    toJson(): Record<string, any> {
      return {
        name: this.name,
        official_name: this.officialName,
        slug: this.slug,
        iso2: this.iso2,
        iso3: this.iso3,
        numeric_code: this.numericCode,
        country_code: this.countryCode,
        currency_code: this.currencyCode,
        currency_name: this.currencyName,
        currency_symbol: this.currencySymbol,
        min_length_phone: this.minLengthPhone,
        max_length_phone: this.maxLengthPhone,
        phone_format: this.phoneFormat,
        postal_code_format: this.postalCodeFormat,
        uses_postal_code: this.usesPostalCode,
      };
    }
  
    // Méthode pour copier avec modifications
    copyWith(props: Partial<CountryProps>): Country {
      return new Country({
        name: props.name ?? this.name,
        officialName: props.officialName ?? this.officialName,
        slug: props.slug ?? this.slug,
        iso2: props.iso2 ?? this.iso2,
        iso3: props.iso3 ?? this.iso3,
        numericCode: props.numericCode ?? this.numericCode,
        countryCode: props.countryCode ?? this.countryCode,
        currencyCode: props.currencyCode ?? this.currencyCode,
        currencyName: props.currencyName ?? this.currencyName,
        currencySymbol: props.currencySymbol ?? this.currencySymbol,
        minLengthPhone: props.minLengthPhone ?? this.minLengthPhone,
        maxLengthPhone: props.maxLengthPhone ?? this.maxLengthPhone,
        phoneFormat: props.phoneFormat ?? this.phoneFormat,
        postalCodeFormat: props.postalCodeFormat ?? this.postalCodeFormat,
        usesPostalCode: props.usesPostalCode ?? this.usesPostalCode,
      });
    }
  
    toString(): string {
      return `Country(name: ${this.name}, iso2: ${this.iso2}, iso3: ${this.iso3}, countryCode: ${this.countryCode})`;
    }
  }
    
  export class Countries {
    static allCountries: Country[] = [
      new Country({
        name: "Afghanistan",
        officialName: "Islamic Republic of Afghanistan",
        slug: "afghanistan",
        iso2: "AF",
        iso3: "AFG",
        numericCode: "004",
        countryCode: "93",
        currencyCode: "AFN",
        currencyName: "Afghan Afghani",
        currencySymbol: "؋",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Albania",
        officialName: "Republic of Albania",
        slug: "albania",
        iso2: "AL",
        iso3: "ALB",
        numericCode: "008",
        countryCode: "355",
        currencyCode: "ALL",
        currencyName: "Albanian Lek",
        currencySymbol: "L",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Algeria",
        officialName: "People's Democratic Republic of Algeria",
        slug: "algeria",
        iso2: "DZ",
        iso3: "DZA",
        numericCode: "012",
        countryCode: "213",
        currencyCode: "DZD",
        currencyName: "Algerian Dinar",
        currencySymbol: "د.ج",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XX XX XX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Andorra",
        officialName: "Principality of Andorra",
        slug: "andorra",
        iso2: "AD",
        iso3: "AND",
        numericCode: "020",
        countryCode: "376",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 6,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Angola",
        officialName: "Republic of Angola",
        slug: "angola",
        iso2: "AO",
        iso3: "AGO",
        numericCode: "024",
        countryCode: "244",
        currencyCode: "AOA",
        currencyName: "Angolan Kwanza",
        currencySymbol: "Kz",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Antigua and Barbuda",
        officialName: "Antigua and Barbuda",
        slug: "antigua-and-barbuda",
        iso2: "AG",
        iso3: "ATG",
        numericCode: "028",
        countryCode: "1268",
        currencyCode: "XCD",
        currencyName: "East Caribbean Dollar",
        currencySymbol: "$",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "(XXX) XXX-XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Argentina",
        officialName: "Argentine Republic",
        slug: "argentina",
        iso2: "AR",
        iso3: "ARG",
        numericCode: "032",
        countryCode: "54",
        currencyCode: "ARS",
        currencyName: "Argentine Peso",
        currencySymbol: "$",
        minLengthPhone: 10,
        maxLengthPhone: 11,
        phoneFormat: "XX XXXX-XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Armenia",
        officialName: "Republic of Armenia",
        slug: "armenia",
        iso2: "AM",
        iso3: "ARM",
        numericCode: "051",
        countryCode: "374",
        currencyCode: "AMD",
        currencyName: "Armenian Dram",
        currencySymbol: "֏",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Australia",
        officialName: "Commonwealth of Australia",
        slug: "australia",
        iso2: "AU",
        iso3: "AUS",
        numericCode: "036",
        countryCode: "61",
        currencyCode: "AUD",
        currencyName: "Australian Dollar",
        currencySymbol: "$",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Austria",
        officialName: "Republic of Austria",
        slug: "austria",
        iso2: "AT",
        iso3: "AUT",
        numericCode: "040",
        countryCode: "43",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 10,
        maxLengthPhone: 13,
        phoneFormat: "XXX XXXXXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Azerbaijan",
        officialName: "Republic of Azerbaijan",
        slug: "azerbaijan",
        iso2: "AZ",
        iso3: "AZE",
        numericCode: "031",
        countryCode: "994",
        currencyCode: "AZN",
        currencyName: "Azerbaijani Manat",
        currencySymbol: "₼",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XX XX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Bahamas",
        officialName: "Commonwealth of The Bahamas",
        slug: "bahamas",
        iso2: "BS",
        iso3: "BHS",
        numericCode: "044",
        countryCode: "1242",
        currencyCode: "BSD",
        currencyName: "Bahamian Dollar",
        currencySymbol: "$",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "(XXX) XXX-XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Bahrain",
        officialName: "Kingdom of Bahrain",
        slug: "bahrain",
        iso2: "BH",
        iso3: "BHR",
        numericCode: "048",
        countryCode: "973",
        currencyCode: "BHD",
        currencyName: "Bahraini Dinar",
        currencySymbol: ".د.ب",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Bangladesh",
        officialName: "People's Republic of Bangladesh",
        slug: "bangladesh",
        iso2: "BD",
        iso3: "BGD",
        numericCode: "050",
        countryCode: "880",
        currencyCode: "BDT",
        currencyName: "Bangladeshi Taka",
        currencySymbol: "৳",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXXX-XXXXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Barbados",
        officialName: "Barbados",
        slug: "barbados",
        iso2: "BB",
        iso3: "BRB",
        numericCode: "052",
        countryCode: "1246",
        currencyCode: "BBD",
        currencyName: "Barbadian Dollar",
        currencySymbol: "$",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "(XXX) XXX-XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Belarus",
        officialName: "Republic of Belarus",
        slug: "belarus",
        iso2: "BY",
        iso3: "BLR",
        numericCode: "112",
        countryCode: "375",
        currencyCode: "BYN",
        currencyName: "Belarusian Ruble",
        currencySymbol: "Br",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX-XX-XX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Belgium",
        officialName: "Kingdom of Belgium",
        slug: "belgium",
        iso2: "BE",
        iso3: "BEL",
        numericCode: "056",
        countryCode: "32",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XX XX XX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Belize",
        officialName: "Belize",
        slug: "belize",
        iso2: "BZ",
        iso3: "BLZ",
        numericCode: "084",
        countryCode: "501",
        currencyCode: "BZD",
        currencyName: "Belize Dollar",
        currencySymbol: "$",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX-XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Benin",
        officialName: "Republic of Benin",
        slug: "benin",
        iso2: "BJ",
        iso3: "BEN",
        numericCode: "204",
        countryCode: "229",
        currencyCode: "XOF",
        currencyName: "West African CFA Franc",
        currencySymbol: "CFA",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XX XX XX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Bhutan",
        officialName: "Kingdom of Bhutan",
        slug: "bhutan",
        iso2: "BT",
        iso3: "BTN",
        numericCode: "064",
        countryCode: "975",
        currencyCode: "BTN",
        currencyName: "Bhutanese Ngultrum",
        currencySymbol: "Nu.",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Bolivia",
        officialName: "Plurinational State of Bolivia",
        slug: "bolivia",
        iso2: "BO",
        iso3: "BOL",
        numericCode: "068",
        countryCode: "591",
        currencyCode: "BOB",
        currencyName: "Bolivian Boliviano",
        currencySymbol: "Bs.",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "X XXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Bosnia and Herzegovina",
        officialName: "Bosnia and Herzegovina",
        slug: "bosnia-and-herzegovina",
        iso2: "BA",
        iso3: "BIH",
        numericCode: "070",
        countryCode: "387",
        currencyCode: "BAM",
        currencyName: "Bosnia-Herzegovina Convertible Mark",
        currencySymbol: "KM",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XXX-XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Botswana",
        officialName: "Republic of Botswana",
        slug: "botswana",
        iso2: "BW",
        iso3: "BWA",
        numericCode: "072",
        countryCode: "267",
        currencyCode: "BWP",
        currencyName: "Botswana Pula",
        currencySymbol: "P",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XXX XXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Brazil",
        officialName: "Federative Republic of Brazil",
        slug: "brazil",
        iso2: "BR",
        iso3: "BRA",
        numericCode: "076",
        countryCode: "55",
        currencyCode: "BRL",
        currencyName: "Brazilian Real",
        currencySymbol: "R$",
        minLengthPhone: 11,
        maxLengthPhone: 11,
        phoneFormat: "(XX) XXXXX-XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Brunei",
        officialName: "Brunei Darussalam",
        slug: "brunei",
        iso2: "BN",
        iso3: "BRN",
        numericCode: "096",
        countryCode: "673",
        currencyCode: "BND",
        currencyName: "Brunei Dollar",
        currencySymbol: "$",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Bulgaria",
        officialName: "Republic of Bulgaria",
        slug: "bulgaria",
        iso2: "BG",
        iso3: "BGR",
        numericCode: "100",
        countryCode: "359",
        currencyCode: "BGN",
        currencyName: "Bulgarian Lev",
        currencySymbol: "лв",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Burkina Faso",
        officialName: "Burkina Faso",
        slug: "burkina-faso",
        iso2: "BF",
        iso3: "BFA",
        numericCode: "854",
        countryCode: "226",
        currencyCode: "XOF",
        currencyName: "West African CFA Franc",
        currencySymbol: "CFA",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XX XX XX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Burundi",
        officialName: "Republic of Burundi",
        slug: "burundi",
        iso2: "BI",
        iso3: "BDI",
        numericCode: "108",
        countryCode: "257",
        currencyCode: "BIF",
        currencyName: "Burundian Franc",
        currencySymbol: "FBu",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XX XX XX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Cambodia",
        officialName: "Kingdom of Cambodia",
        slug: "cambodia",
        iso2: "KH",
        iso3: "KHM",
        numericCode: "116",
        countryCode: "855",
        currencyCode: "KHR",
        currencyName: "Cambodian Riel",
        currencySymbol: "៛",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Cameroon",
        officialName: "Republic of Cameroon",
        slug: "cameroon",
        iso2: "CM",
        iso3: "CMR",
        numericCode: "120",
        countryCode: "237",
        currencyCode: "XAF",
        currencyName: "Central African CFA Franc",
        currencySymbol: "FCFA",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "X XX XX XX XX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Canada",
        officialName: "Canada",
        slug: "canada",
        iso2: "CA",
        iso3: "CAN",
        numericCode: "124",
        countryCode: "1",
        currencyCode: "CAD",
        currencyName: "Canadian Dollar",
        currencySymbol: "C$",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "(XXX) XXX-XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Cape Verde",
        officialName: "Republic of Cabo Verde",
        slug: "cape-verde",
        iso2: "CV",
        iso3: "CPV",
        numericCode: "132",
        countryCode: "238",
        currencyCode: "CVE",
        currencyName: "Cape Verdean Escudo",
        currencySymbol: "$",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX XX XX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Central African Republic",
        officialName: "Central African Republic",
        slug: "central-african-republic",
        iso2: "CF",
        iso3: "CAF",
        numericCode: "140",
        countryCode: "236",
        currencyCode: "XAF",
        currencyName: "Central African CFA Franc",
        currencySymbol: "FCFA",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XX XX XX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Chad",
        officialName: "Republic of Chad",
        slug: "chad",
        iso2: "TD",
        iso3: "TCD",
        numericCode: "148",
        countryCode: "235",
        currencyCode: "XAF",
        currencyName: "Central African CFA Franc",
        currencySymbol: "FCFA",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XX XX XX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Chile",
        officialName: "Republic of Chile",
        slug: "chile",
        iso2: "CL",
        iso3: "CHL",
        numericCode: "152",
        countryCode: "56",
        currencyCode: "CLP",
        currencyName: "Chilean Peso",
        currencySymbol: "$",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "X XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "China",
        officialName: "People's Republic of China",
        slug: "china",
        iso2: "CN",
        iso3: "CHN",
        numericCode: "156",
        countryCode: "86",
        currencyCode: "CNY",
        currencyName: "Chinese Yuan",
        currencySymbol: "¥",
        minLengthPhone: 11,
        maxLengthPhone: 11,
        phoneFormat: "XXX XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Colombia",
        officialName: "Republic of Colombia",
        slug: "colombia",
        iso2: "CO",
        iso3: "COL",
        numericCode: "170",
        countryCode: "57",
        currencyCode: "COP",
        currencyName: "Colombian Peso",
        currencySymbol: "$",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Comoros",
        officialName: "Union of the Comoros",
        slug: "comoros",
        iso2: "KM",
        iso3: "COM",
        numericCode: "174",
        countryCode: "269",
        currencyCode: "KMF",
        currencyName: "Comorian Franc",
        currencySymbol: "CF",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX XX XX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Congo",
        officialName: "Republic of the Congo",
        slug: "congo",
        iso2: "CG",
        iso3: "COG",
        numericCode: "178",
        countryCode: "242",
        currencyCode: "XAF",
        currencyName: "Central African CFA Franc",
        currencySymbol: "FCFA",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Congo (Democratic Republic)",
        officialName: "Democratic Republic of the Congo",
        slug: "congo-democratic-republic",
        iso2: "CD",
        iso3: "COD",
        numericCode: "180",
        countryCode: "243",
        currencyCode: "CDF",
        currencyName: "Congolese Franc",
        currencySymbol: "FC",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Costa Rica",
        officialName: "Republic of Costa Rica",
        slug: "costa-rica",
        iso2: "CR",
        iso3: "CRI",
        numericCode: "188",
        countryCode: "506",
        currencyCode: "CRC",
        currencyName: "Costa Rican Colón",
        currencySymbol: "₡",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Cote d'Ivoire",
        officialName: "Republic of Côte d'Ivoire",
        slug: "cote-divoire",
        iso2: "CI",
        iso3: "CIV",
        numericCode: "384",
        countryCode: "225",
        currencyCode: "XOF",
        currencyName: "West African CFA Franc",
        currencySymbol: "CFA",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XX XX XX XX XX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Croatia",
        officialName: "Republic of Croatia",
        slug: "croatia",
        iso2: "HR",
        iso3: "HRV",
        numericCode: "191",
        countryCode: "385",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Cuba",
        officialName: "Republic of Cuba",
        slug: "cuba",
        iso2: "CU",
        iso3: "CUB",
        numericCode: "192",
        countryCode: "53",
        currencyCode: "CUP",
        currencyName: "Cuban Peso",
        currencySymbol: "$",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "X XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Cyprus",
        officialName: "Republic of Cyprus",
        slug: "cyprus",
        iso2: "CY",
        iso3: "CYP",
        numericCode: "196",
        countryCode: "357",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Czech Republic",
        officialName: "Czech Republic",
        slug: "czech-republic",
        iso2: "CZ",
        iso3: "CZE",
        numericCode: "203",
        countryCode: "420",
        currencyCode: "CZK",
        currencyName: "Czech Koruna",
        currencySymbol: "Kč",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Denmark",
        officialName: "Kingdom of Denmark",
        slug: "denmark",
        iso2: "DK",
        iso3: "DNK",
        numericCode: "208",
        countryCode: "45",
        currencyCode: "DKK",
        currencyName: "Danish Krone",
        currencySymbol: "kr",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XX XX XX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Djibouti",
        officialName: "Republic of Djibouti",
        slug: "djibouti",
        iso2: "DJ",
        iso3: "DJI",
        numericCode: "262",
        countryCode: "253",
        currencyCode: "DJF",
        currencyName: "Djiboutian Franc",
        currencySymbol: "Fdj",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XX XX XX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Dominica",
        officialName: "Commonwealth of Dominica",
        slug: "dominica",
        iso2: "DM",
        iso3: "DMA",
        numericCode: "212",
        countryCode: "1767",
        currencyCode: "XCD",
        currencyName: "East Caribbean Dollar",
        currencySymbol: "$",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "(XXX) XXX-XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Dominican Republic",
        officialName: "Dominican Republic",
        slug: "dominican-republic",
        iso2: "DO",
        iso3: "DOM",
        numericCode: "214",
        countryCode: "1809",
        currencyCode: "DOP",
        currencyName: "Dominican Peso",
        currencySymbol: "$",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "(XXX) XXX-XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Ecuador",
        officialName: "Republic of Ecuador",
        slug: "ecuador",
        iso2: "EC",
        iso3: "ECU",
        numericCode: "218",
        countryCode: "593",
        currencyCode: "USD",
        currencyName: "US Dollar",
        currencySymbol: "$",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Egypt",
        officialName: "Arab Republic of Egypt",
        slug: "egypt",
        iso2: "EG",
        iso3: "EGY",
        numericCode: "818",
        countryCode: "20",
        currencyCode: "EGP",
        currencyName: "Egyptian Pound",
        currencySymbol: "£",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "El Salvador",
        officialName: "Republic of El Salvador",
        slug: "el-salvador",
        iso2: "SV",
        iso3: "SLV",
        numericCode: "222",
        countryCode: "503",
        currencyCode: "USD",
        currencyName: "US Dollar",
        currencySymbol: "$",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Equatorial Guinea",
        officialName: "Republic of Equatorial Guinea",
        slug: "equatorial-guinea",
        iso2: "GQ",
        iso3: "GNQ",
        numericCode: "226",
        countryCode: "240",
        currencyCode: "XAF",
        currencyName: "Central African CFA Franc",
        currencySymbol: "FCFA",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Eritrea",
        officialName: "State of Eritrea",
        slug: "eritrea",
        iso2: "ER",
        iso3: "ERI",
        numericCode: "232",
        countryCode: "291",
        currencyCode: "ERN",
        currencyName: "Eritrean Nakfa",
        currencySymbol: "Nfk",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "X XXX XXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Estonia",
        officialName: "Republic of Estonia",
        slug: "estonia",
        iso2: "EE",
        iso3: "EST",
        numericCode: "233",
        countryCode: "372",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Eswatini",
        officialName: "Kingdom of Eswatini",
        slug: "eswatini",
        iso2: "SZ",
        iso3: "SWZ",
        numericCode: "748",
        countryCode: "268",
        currencyCode: "SZL",
        currencyName: "Swazi Lilangeni",
        currencySymbol: "L",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Ethiopia",
        officialName: "Federal Democratic Republic of Ethiopia",
        slug: "ethiopia",
        iso2: "ET",
        iso3: "ETH",
        numericCode: "231",
        countryCode: "251",
        currencyCode: "ETB",
        currencyName: "Ethiopian Birr",
        currencySymbol: "Br",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Fiji",
        officialName: "Republic of Fiji",
        slug: "fiji",
        iso2: "FJ",
        iso3: "FJI",
        numericCode: "242",
        countryCode: "679",
        currencyCode: "FJD",
        currencyName: "Fijian Dollar",
        currencySymbol: "$",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Finland",
        officialName: "Republic of Finland",
        slug: "finland",
        iso2: "FI",
        iso3: "FIN",
        numericCode: "246",
        countryCode: "358",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 9,
        maxLengthPhone: 10,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "France",
        officialName: "French Republic",
        slug: "france",
        iso2: "FR",
        iso3: "FRA",
        numericCode: "250",
        countryCode: "33",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XX XX XX XX XX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Gabon",
        officialName: "Gabonese Republic",
        slug: "gabon",
        iso2: "GA",
        iso3: "GAB",
        numericCode: "266",
        countryCode: "241",
        currencyCode: "XAF",
        currencyName: "Central African CFA Franc",
        currencySymbol: "FCFA",
        minLengthPhone: 7,
        maxLengthPhone: 8,
        phoneFormat: "X XX XX XX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Gambia",
        officialName: "Republic of The Gambia",
        slug: "gambia",
        iso2: "GM",
        iso3: "GMB",
        numericCode: "270",
        countryCode: "220",
        currencyCode: "GMD",
        currencyName: "Gambian Dalasi",
        currencySymbol: "D",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Georgia",
        officialName: "Georgia",
        slug: "georgia",
        iso2: "GE",
        iso3: "GEO",
        numericCode: "268",
        countryCode: "995",
        currencyCode: "GEL",
        currencyName: "Georgian Lari",
        currencySymbol: "₾",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Germany",
        officialName: "Federal Republic of Germany",
        slug: "germany",
        iso2: "DE",
        iso3: "DEU",
        numericCode: "276",
        countryCode: "49",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 10,
        maxLengthPhone: 11,
        phoneFormat: "XXX XXXXXXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Ghana",
        officialName: "Republic of Ghana",
        slug: "ghana",
        iso2: "GH",
        iso3: "GHA",
        numericCode: "288",
        countryCode: "233",
        currencyCode: "GHS",
        currencyName: "Ghanaian Cedi",
        currencySymbol: "₵",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Greece",
        officialName: "Hellenic Republic",
        slug: "greece",
        iso2: "GR",
        iso3: "GRC",
        numericCode: "300",
        countryCode: "30",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Grenada",
        officialName: "Grenada",
        slug: "grenada",
        iso2: "GD",
        iso3: "GRD",
        numericCode: "308",
        countryCode: "1473",
        currencyCode: "XCD",
        currencyName: "East Caribbean Dollar",
        currencySymbol: "$",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "(XXX) XXX-XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Guatemala",
        officialName: "Republic of Guatemala",
        slug: "guatemala",
        iso2: "GT",
        iso3: "GTM",
        numericCode: "320",
        countryCode: "502",
        currencyCode: "GTQ",
        currencyName: "Guatemalan Quetzal",
        currencySymbol: "Q",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Guinea",
        officialName: "Republic of Guinea",
        slug: "guinea",
        iso2: "GN",
        iso3: "GIN",
        numericCode: "324",
        countryCode: "224",
        currencyCode: "GNF",
        currencyName: "Guinean Franc",
        currencySymbol: "FG",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX-XX-XX-XX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Guinea-Bissau",
        officialName: "Republic of Guinea-Bissau",
        slug: "guinea-bissau",
        iso2: "GW",
        iso3: "GNB",
        numericCode: "624",
        countryCode: "245",
        currencyCode: "XOF",
        currencyName: "West African CFA Franc",
        currencySymbol: "CFA",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Guyana",
        officialName: "Co-operative Republic of Guyana",
        slug: "guyana",
        iso2: "GY",
        iso3: "GUY",
        numericCode: "328",
        countryCode: "592",
        currencyCode: "GYD",
        currencyName: "Guyanese Dollar",
        currencySymbol: "$",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Haiti",
        officialName: "Republic of Haiti",
        slug: "haiti",
        iso2: "HT",
        iso3: "HTI",
        numericCode: "332",
        countryCode: "509",
        currencyCode: "HTG",
        currencyName: "Haitian Gourde",
        currencySymbol: "G",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Honduras",
        officialName: "Republic of Honduras",
        slug: "honduras",
        iso2: "HN",
        iso3: "HND",
        numericCode: "340",
        countryCode: "504",
        currencyCode: "HNL",
        currencyName: "Honduran Lempira",
        currencySymbol: "L",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX-XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Hungary",
        officialName: "Hungary",
        slug: "hungary",
        iso2: "HU",
        iso3: "HUN",
        numericCode: "348",
        countryCode: "36",
        currencyCode: "HUF",
        currencyName: "Hungarian Forint",
        currencySymbol: "Ft",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Iceland",
        officialName: "Iceland",
        slug: "iceland",
        iso2: "IS",
        iso3: "ISL",
        numericCode: "352",
        countryCode: "354",
        currencyCode: "ISK",
        currencyName: "Icelandic Króna",
        currencySymbol: "kr",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "India",
        officialName: "Republic of India",
        slug: "india",
        iso2: "IN",
        iso3: "IND",
        numericCode: "356",
        countryCode: "91",
        currencyCode: "INR",
        currencyName: "Indian Rupee",
        currencySymbol: "₹",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXXXX XXXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Indonesia",
        officialName: "Republic of Indonesia",
        slug: "indonesia",
        iso2: "ID",
        iso3: "IDN",
        numericCode: "360",
        countryCode: "62",
        currencyCode: "IDR",
        currencyName: "Indonesian Rupiah",
        currencySymbol: "Rp",
        minLengthPhone: 10,
        maxLengthPhone: 11,
        phoneFormat: "XXX-XXXX-XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Iran",
        officialName: "Islamic Republic of Iran",
        slug: "iran",
        iso2: "IR",
        iso3: "IRN",
        numericCode: "364",
        countryCode: "98",
        currencyCode: "IRR",
        currencyName: "Iranian Rial",
        currencySymbol: "﷼",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Iraq",
        officialName: "Republic of Iraq",
        slug: "iraq",
        iso2: "IQ",
        iso3: "IRQ",
        numericCode: "368",
        countryCode: "964",
        currencyCode: "IQD",
        currencyName: "Iraqi Dinar",
        currencySymbol: "ع.د",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Ireland",
        officialName: "Republic of Ireland",
        slug: "ireland",
        iso2: "IE",
        iso3: "IRL",
        numericCode: "372",
        countryCode: "353",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Israel",
        officialName: "State of Israel",
        slug: "israel",
        iso2: "IL",
        iso3: "ISR",
        numericCode: "376",
        countryCode: "972",
        currencyCode: "ILS",
        currencyName: "Israeli New Shekel",
        currencySymbol: "₪",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX-XXX-XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Italy",
        officialName: "Italian Republic",
        slug: "italy",
        iso2: "IT",
        iso3: "ITA",
        numericCode: "380",
        countryCode: "39",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Jamaica",
        officialName: "Jamaica",
        slug: "jamaica",
        iso2: "JM",
        iso3: "JAM",
        numericCode: "388",
        countryCode: "1876",
        currencyCode: "JMD",
        currencyName: "Jamaican Dollar",
        currencySymbol: "$",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "(XXX) XXX-XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Japan",
        officialName: "Japan",
        slug: "japan",
        iso2: "JP",
        iso3: "JPN",
        numericCode: "392",
        countryCode: "81",
        currencyCode: "JPY",
        currencyName: "Japanese Yen",
        currencySymbol: "¥",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XX-XXXX-XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Jordan",
        officialName: "Hashemite Kingdom of Jordan",
        slug: "jordan",
        iso2: "JO",
        iso3: "JOR",
        numericCode: "400",
        countryCode: "962",
        currencyCode: "JOD",
        currencyName: "Jordanian Dinar",
        currencySymbol: "د.ا",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "X XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Kazakhstan",
        officialName: "Republic of Kazakhstan",
        slug: "kazakhstan",
        iso2: "KZ",
        iso3: "KAZ",
        numericCode: "398",
        countryCode: "7",
        currencyCode: "KZT",
        currencyName: "Kazakhstani Tenge",
        currencySymbol: "₸",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXX XXX XX XX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Kenya",
        officialName: "Republic of Kenya",
        slug: "kenya",
        iso2: "KE",
        iso3: "KEN",
        numericCode: "404",
        countryCode: "254",
        currencyCode: "KES",
        currencyName: "Kenyan Shilling",
        currencySymbol: "KSh",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXX XXXXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Kiribati",
        officialName: "Republic of Kiribati",
        slug: "kiribati",
        iso2: "KI",
        iso3: "KIR",
        numericCode: "296",
        countryCode: "686",
        currencyCode: "AUD",
        currencyName: "Australian Dollar",
        currencySymbol: "$",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Korea (North)",
        officialName: "Democratic People's Republic of Korea",
        slug: "north-korea",
        iso2: "KP",
        iso3: "PRK",
        numericCode: "408",
        countryCode: "850",
        currencyCode: "KPW",
        currencyName: "North Korean Won",
        currencySymbol: "₩",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXX XXXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Korea (South)",
        officialName: "Republic of Korea",
        slug: "south-korea",
        iso2: "KR",
        iso3: "KOR",
        numericCode: "410",
        countryCode: "82",
        currencyCode: "KRW",
        currencyName: "South Korean Won",
        currencySymbol: "₩",
        minLengthPhone: 10,
        maxLengthPhone: 11,
        phoneFormat: "XX-XXXX-XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Kuwait",
        officialName: "State of Kuwait",
        slug: "kuwait",
        iso2: "KW",
        iso3: "KWT",
        numericCode: "414",
        countryCode: "965",
        currencyCode: "KWD",
        currencyName: "Kuwaiti Dinar",
        currencySymbol: "د.ك",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Kyrgyzstan",
        officialName: "Kyrgyz Republic",
        slug: "kyrgyzstan",
        iso2: "KG",
        iso3: "KGZ",
        numericCode: "417",
        countryCode: "996",
        currencyCode: "KGS",
        currencyName: "Kyrgyzstani Som",
        currencySymbol: "с",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXXXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Laos",
        officialName: "Lao People's Democratic Republic",
        slug: "laos",
        iso2: "LA",
        iso3: "LAO",
        numericCode: "418",
        countryCode: "856",
        currencyCode: "LAK",
        currencyName: "Lao Kip",
        currencySymbol: "₭",
        minLengthPhone: 9,
        maxLengthPhone: 10,
        phoneFormat: "XX XX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Latvia",
        officialName: "Republic of Latvia",
        slug: "latvia",
        iso2: "LV",
        iso3: "LVA",
        numericCode: "428",
        countryCode: "371",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Lebanon",
        officialName: "Lebanese Republic",
        slug: "lebanon",
        iso2: "LB",
        iso3: "LBN",
        numericCode: "422",
        countryCode: "961",
        currencyCode: "LBP",
        currencyName: "Lebanese Pound",
        currencySymbol: "ل.ل",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Lesotho",
        officialName: "Kingdom of Lesotho",
        slug: "lesotho",
        iso2: "LS",
        iso3: "LSO",
        numericCode: "426",
        countryCode: "266",
        currencyCode: "LSL",
        currencyName: "Lesotho Loti",
        currencySymbol: "L",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Liberia",
        officialName: "Republic of Liberia",
        slug: "liberia",
        iso2: "LR",
        iso3: "LBR",
        numericCode: "430",
        countryCode: "231",
        currencyCode: "LRD",
        currencyName: "Liberian Dollar",
        currencySymbol: "$",
        minLengthPhone: 7,
        maxLengthPhone: 8,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Libya",
        officialName: "State of Libya",
        slug: "libya",
        iso2: "LY",
        iso3: "LBY",
        numericCode: "434",
        countryCode: "218",
        currencyCode: "LYD",
        currencyName: "Libyan Dinar",
        currencySymbol: "ل.د",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XX-XXX-XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Liechtenstein",
        officialName: "Principality of Liechtenstein",
        slug: "liechtenstein",
        iso2: "LI",
        iso3: "LIE",
        numericCode: "438",
        countryCode: "423",
        currencyCode: "CHF",
        currencyName: "Swiss Franc",
        currencySymbol: "Fr",
        minLengthPhone: 7,
        maxLengthPhone: 9,
        phoneFormat: "XXX XX XX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Lithuania",
        officialName: "Republic of Lithuania",
        slug: "lithuania",
        iso2: "LT",
        iso3: "LTU",
        numericCode: "440",
        countryCode: "370",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXX XXXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Luxembourg",
        officialName: "Grand Duchy of Luxembourg",
        slug: "luxembourg",
        iso2: "LU",
        iso3: "LUX",
        numericCode: "442",
        countryCode: "352",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Madagascar",
        officialName: "Republic of Madagascar",
        slug: "madagascar",
        iso2: "MG",
        iso3: "MDG",
        numericCode: "450",
        countryCode: "261",
        currencyCode: "MGA",
        currencyName: "Malagasy Ariary",
        currencySymbol: "Ar",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XX XX XXX XX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Malawi",
        officialName: "Republic of Malawi",
        slug: "malawi",
        iso2: "MW",
        iso3: "MWI",
        numericCode: "454",
        countryCode: "265",
        currencyCode: "MWK",
        currencyName: "Malawian Kwacha",
        currencySymbol: "MK",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "X XXXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Malaysia",
        officialName: "Malaysia",
        slug: "malaysia",
        iso2: "MY",
        iso3: "MYS",
        numericCode: "458",
        countryCode: "60",
        currencyCode: "MYR",
        currencyName: "Malaysian Ringgit",
        currencySymbol: "RM",
        minLengthPhone: 9,
        maxLengthPhone: 10,
        phoneFormat: "XX-XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Maldives",
        officialName: "Republic of Maldives",
        slug: "maldives",
        iso2: "MV",
        iso3: "MDV",
        numericCode: "462",
        countryCode: "960",
        currencyCode: "MVR",
        currencyName: "Maldivian Rufiyaa",
        currencySymbol: "Rf",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX-XXXX",
        usesPostalCode: true,
      }),
      // mali
      new Country({
        name: "Mali",
        officialName: "Republic of Mali",
        slug: "mali",
        iso2: "ML",
        iso3: "MLI",
        numericCode: "466",
        countryCode: "223",
        currencyCode: "XOF",
        currencyName: "West African CFA Franc",
        currencySymbol: "CFA",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Malta",
        officialName: "Republic of Malta",
        slug: "malta",
        iso2: "MT",
        iso3: "MLT",
        numericCode: "470",
        countryCode: "356",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Marshall Islands",
        officialName: "Republic of the Marshall Islands",
        slug: "marshall-islands",
        iso2: "MH",
        iso3: "MHL",
        numericCode: "584",
        countryCode: "692",
        currencyCode: "USD",
        currencyName: "US Dollar",
        currencySymbol: "$",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX-XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Mauritania",
        officialName: "Islamic Republic of Mauritania",
        slug: "mauritania",
        iso2: "MR",
        iso3: "MRT",
        numericCode: "478",
        countryCode: "222",
        currencyCode: "MRU",
        currencyName: "Mauritanian Ouguiya",
        currencySymbol: "UM",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XX XX XX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Mauritius",
        officialName: "Republic of Mauritius",
        slug: "mauritius",
        iso2: "MU",
        iso3: "MUS",
        numericCode: "480",
        countryCode: "230",
        currencyCode: "MUR",
        currencyName: "Mauritian Rupee",
        currencySymbol: "₨",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Mexico",
        officialName: "United Mexican States",
        slug: "mexico",
        iso2: "MX",
        iso3: "MEX",
        numericCode: "484",
        countryCode: "52",
        currencyCode: "MXN",
        currencyName: "Mexican Peso",
        currencySymbol: "$",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Micronesia",
        officialName: "Federated States of Micronesia",
        slug: "micronesia",
        iso2: "FM",
        iso3: "FSM",
        numericCode: "583",
        countryCode: "691",
        currencyCode: "USD",
        currencyName: "US Dollar",
        currencySymbol: "$",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Moldova",
        officialName: "Republic of Moldova",
        slug: "moldova",
        iso2: "MD",
        iso3: "MDA",
        numericCode: "498",
        countryCode: "373",
        currencyCode: "MDL",
        currencyName: "Moldovan Leu",
        currencySymbol: "L",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Monaco",
        officialName: "Principality of Monaco",
        slug: "monaco",
        iso2: "MC",
        iso3: "MCO",
        numericCode: "492",
        countryCode: "377",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 8,
        maxLengthPhone: 9,
        phoneFormat: "XX XX XX XX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Mongolia",
        officialName: "Mongolia",
        slug: "mongolia",
        iso2: "MN",
        iso3: "MNG",
        numericCode: "496",
        countryCode: "976",
        currencyCode: "MNT",
        currencyName: "Mongolian Tugrik",
        currencySymbol: "₮",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Montenegro",
        officialName: "Montenegro",
        slug: "montenegro",
        iso2: "ME",
        iso3: "MNE",
        numericCode: "499",
        countryCode: "382",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Morocco",
        officialName: "Kingdom of Morocco",
        slug: "morocco",
        iso2: "MA",
        iso3: "MAR",
        numericCode: "504",
        countryCode: "212",
        currencyCode: "MAD",
        currencyName: "Moroccan Dirham",
        currencySymbol: "د.م.",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX-XXXXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Mozambique",
        officialName: "Republic of Mozambique",
        slug: "mozambique",
        iso2: "MZ",
        iso3: "MOZ",
        numericCode: "508",
        countryCode: "258",
        currencyCode: "MZN",
        currencyName: "Mozambican Metical",
        currencySymbol: "MT",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Myanmar",
        officialName: "Republic of the Union of Myanmar",
        slug: "myanmar",
        iso2: "MM",
        iso3: "MMR",
        numericCode: "104",
        countryCode: "95",
        currencyCode: "MMK",
        currencyName: "Myanmar Kyat",
        currencySymbol: "K",
        minLengthPhone: 9,
        maxLengthPhone: 10,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Namibia",
        officialName: "Republic of Namibia",
        slug: "namibia",
        iso2: "NA",
        iso3: "NAM",
        numericCode: "516",
        countryCode: "264",
        currencyCode: "NAD",
        currencyName: "Namibian Dollar",
        currencySymbol: "$",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Nauru",
        officialName: "Republic of Nauru",
        slug: "nauru",
        iso2: "NR",
        iso3: "NRU",
        numericCode: "520",
        countryCode: "674",
        currencyCode: "AUD",
        currencyName: "Australian Dollar",
        currencySymbol: "$",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Nepal",
        officialName: "Federal Democratic Republic of Nepal",
        slug: "nepal",
        iso2: "NP",
        iso3: "NPL",
        numericCode: "524",
        countryCode: "977",
        currencyCode: "NPR",
        currencyName: "Nepalese Rupee",
        currencySymbol: "₨",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XX-XXXX-XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Netherlands",
        officialName: "Kingdom of the Netherlands",
        slug: "netherlands",
        iso2: "NL",
        iso3: "NLD",
        numericCode: "528",
        countryCode: "31",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "New Zealand",
        officialName: "New Zealand",
        slug: "new-zealand",
        iso2: "NZ",
        iso3: "NZL",
        numericCode: "554",
        countryCode: "64",
        currencyCode: "NZD",
        currencyName: "New Zealand Dollar",
        currencySymbol: "$",
        minLengthPhone: 9,
        maxLengthPhone: 10,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Nicaragua",
        officialName: "Republic of Nicaragua",
        slug: "nicaragua",
        iso2: "NI",
        iso3: "NIC",
        numericCode: "558",
        countryCode: "505",
        currencyCode: "NIO",
        currencyName: "Nicaraguan Córdoba",
        currencySymbol: "C$",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Niger",
        officialName: "Republic of Niger",
        slug: "niger",
        iso2: "NE",
        iso3: "NER",
        numericCode: "562",
        countryCode: "227",
        currencyCode: "XOF",
        currencyName: "West African CFA Franc",
        currencySymbol: "CFA",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XX XX XX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Nigeria",
        officialName: "Federal Republic of Nigeria",
        slug: "nigeria",
        iso2: "NG",
        iso3: "NGA",
        numericCode: "566",
        countryCode: "234",
        currencyCode: "NGN",
        currencyName: "Nigerian Naira",
        currencySymbol: "₦",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "North Macedonia",
        officialName: "Republic of North Macedonia",
        slug: "north-macedonia",
        iso2: "MK",
        iso3: "MKD",
        numericCode: "807",
        countryCode: "389",
        currencyCode: "MKD",
        currencyName: "Macedonian Denar",
        currencySymbol: "ден",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Norway",
        officialName: "Kingdom of Norway",
        slug: "norway",
        iso2: "NO",
        iso3: "NOR",
        numericCode: "578",
        countryCode: "47",
        currencyCode: "NOK",
        currencyName: "Norwegian Krone",
        currencySymbol: "kr",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXX XX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Oman",
        officialName: "Sultanate of Oman",
        slug: "oman",
        iso2: "OM",
        iso3: "OMN",
        numericCode: "512",
        countryCode: "968",
        currencyCode: "OMR",
        currencyName: "Omani Rial",
        currencySymbol: "ر.ع.",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Pakistan",
        officialName: "Islamic Republic of Pakistan",
        slug: "pakistan",
        iso2: "PK",
        iso3: "PAK",
        numericCode: "586",
        countryCode: "92",
        currencyCode: "PKR",
        currencyName: "Pakistani Rupee",
        currencySymbol: "₨",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Palau",
        officialName: "Republic of Palau",
        slug: "palau",
        iso2: "PW",
        iso3: "PLW",
        numericCode: "585",
        countryCode: "680",
        currencyCode: "USD",
        currencyName: "US Dollar",
        currencySymbol: "$",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Palestine",
        officialName: "State of Palestine",
        slug: "palestine",
        iso2: "PS",
        iso3: "PSE",
        numericCode: "275",
        countryCode: "970",
        currencyCode: "ILS",
        currencyName: "Israeli New Shekel",
        currencySymbol: "₪",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Panama",
        officialName: "Republic of Panama",
        slug: "panama",
        iso2: "PA",
        iso3: "PAN",
        numericCode: "591",
        countryCode: "507",
        currencyCode: "PAB",
        currencyName: "Panamanian Balboa",
        currencySymbol: "B/.",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX-XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Papua New Guinea",
        officialName: "Independent State of Papua New Guinea",
        slug: "papua-new-guinea",
        iso2: "PG",
        iso3: "PNG",
        numericCode: "598",
        countryCode: "675",
        currencyCode: "PGK",
        currencyName: "Papua New Guinean Kina",
        currencySymbol: "K",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXX XXXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Paraguay",
        officialName: "Republic of Paraguay",
        slug: "paraguay",
        iso2: "PY",
        iso3: "PRY",
        numericCode: "600",
        countryCode: "595",
        currencyCode: "PYG",
        currencyName: "Paraguayan Guarani",
        currencySymbol: "₲",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Peru",
        officialName: "Republic of Peru",
        slug: "peru",
        iso2: "PE",
        iso3: "PER",
        numericCode: "604",
        countryCode: "51",
        currencyCode: "PEN",
        currencyName: "Peruvian Sol",
        currencySymbol: "S/",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Philippines",
        officialName: "Republic of the Philippines",
        slug: "philippines",
        iso2: "PH",
        iso3: "PHL",
        numericCode: "608",
        countryCode: "63",
        currencyCode: "PHP",
        currencyName: "Philippine Peso",
        currencySymbol: "₱",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Poland",
        officialName: "Republic of Poland",
        slug: "poland",
        iso2: "PL",
        iso3: "POL",
        numericCode: "616",
        countryCode: "48",
        currencyCode: "PLN",
        currencyName: "Polish Zloty",
        currencySymbol: "zł",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Portugal",
        officialName: "Portuguese Republic",
        slug: "portugal",
        iso2: "PT",
        iso3: "PRT",
        numericCode: "620",
        countryCode: "351",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Qatar",
        officialName: "State of Qatar",
        slug: "qatar",
        iso2: "QA",
        iso3: "QAT",
        numericCode: "634",
        countryCode: "974",
        currencyCode: "QAR",
        currencyName: "Qatari Riyal",
        currencySymbol: "ر.ق",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Romania",
        officialName: "Romania",
        slug: "romania",
        iso2: "RO",
        iso3: "ROU",
        numericCode: "642",
        countryCode: "40",
        currencyCode: "RON",
        currencyName: "Romanian Leu",
        currencySymbol: "lei",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Russia",
        officialName: "Russian Federation",
        slug: "russia",
        iso2: "RU",
        iso3: "RUS",
        numericCode: "643",
        countryCode: "7",
        currencyCode: "RUB",
        currencyName: "Russian Ruble",
        currencySymbol: "₽",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXX XXX-XX-XX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Rwanda",
        officialName: "Republic of Rwanda",
        slug: "rwanda",
        iso2: "RW",
        iso3: "RWA",
        numericCode: "646",
        countryCode: "250",
        currencyCode: "RWF",
        currencyName: "Rwandan Franc",
        currencySymbol: "FRw",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Saint Kitts and Nevis",
        officialName: "Federation of Saint Christopher and Nevis",
        slug: "saint-kitts-and-nevis",
        iso2: "KN",
        iso3: "KNA",
        numericCode: "659",
        countryCode: "1869",
        currencyCode: "XCD",
        currencyName: "East Caribbean Dollar",
        currencySymbol: "$",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "(XXX) XXX-XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Saint Lucia",
        officialName: "Saint Lucia",
        slug: "saint-lucia",
        iso2: "LC",
        iso3: "LCA",
        numericCode: "662",
        countryCode: "1758",
        currencyCode: "XCD",
        currencyName: "East Caribbean Dollar",
        currencySymbol: "$",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "(XXX) XXX-XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Saint Vincent and the Grenadines",
        officialName: "Saint Vincent and the Grenadines",
        slug: "saint-vincent-and-the-grenadines",
        iso2: "VC",
        iso3: "VCT",
        numericCode: "670",
        countryCode: "1784",
        currencyCode: "XCD",
        currencyName: "East Caribbean Dollar",
        currencySymbol: "$",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "(XXX) XXX-XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Samoa",
        officialName: "Independent State of Samoa",
        slug: "samoa",
        iso2: "WS",
        iso3: "WSM",
        numericCode: "882",
        countryCode: "685",
        currencyCode: "WST",
        currencyName: "Samoan Tala",
        currencySymbol: "T",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "San Marino",
        officialName: "Republic of San Marino",
        slug: "san-marino",
        iso2: "SM",
        iso3: "SMR",
        numericCode: "674",
        countryCode: "378",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXXX XXXXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Sao Tome and Principe",
        officialName: "Democratic Republic of São Tomé and Príncipe",
        slug: "sao-tome-and-principe",
        iso2: "ST",
        iso3: "STP",
        numericCode: "678",
        countryCode: "239",
        currencyCode: "STN",
        currencyName: "São Tomé and Príncipe Dobra",
        currencySymbol: "Db",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Saudi Arabia",
        officialName: "Kingdom of Saudi Arabia",
        slug: "saudi-arabia",
        iso2: "SA",
        iso3: "SAU",
        numericCode: "682",
        countryCode: "966",
        currencyCode: "SAR",
        currencyName: "Saudi Riyal",
        currencySymbol: "ر.س",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Senegal",
        officialName: "Republic of Senegal",
        slug: "senegal",
        iso2: "SN",
        iso3: "SEN",
        numericCode: "686",
        countryCode: "221",
        currencyCode: "XOF",
        currencyName: "West African CFA Franc",
        currencySymbol: "CFA",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XX XX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Serbia",
        officialName: "Republic of Serbia",
        slug: "serbia",
        iso2: "RS",
        iso3: "SRB",
        numericCode: "688",
        countryCode: "381",
        currencyCode: "RSD",
        currencyName: "Serbian Dinar",
        currencySymbol: "дин.",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Seychelles",
        officialName: "Republic of Seychelles",
        slug: "seychelles",
        iso2: "SC",
        iso3: "SYC",
        numericCode: "690",
        countryCode: "248",
        currencyCode: "SCR",
        currencyName: "Seychellois Rupee",
        currencySymbol: "₨",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "X XXX XXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Sierra Leone",
        officialName: "Republic of Sierra Leone",
        slug: "sierra-leone",
        iso2: "SL",
        iso3: "SLE",
        numericCode: "694",
        countryCode: "232",
        currencyCode: "SLL",
        currencyName: "Sierra Leonean Leone",
        currencySymbol: "Le",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XXX XXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Singapore",
        officialName: "Republic of Singapore",
        slug: "singapore",
        iso2: "SG",
        iso3: "SGP",
        numericCode: "702",
        countryCode: "65",
        currencyCode: "SGD",
        currencyName: "Singapore Dollar",
        currencySymbol: "$",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Slovakia",
        officialName: "Slovak Republic",
        slug: "slovakia",
        iso2: "SK",
        iso3: "SVK",
        numericCode: "703",
        countryCode: "421",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Slovenia",
        officialName: "Republic of Slovenia",
        slug: "slovenia",
        iso2: "SI",
        iso3: "SVN",
        numericCode: "705",
        countryCode: "386",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Solomon Islands",
        officialName: "Solomon Islands",
        slug: "solomon-islands",
        iso2: "SB",
        iso3: "SLB",
        numericCode: "090",
        countryCode: "677",
        currencyCode: "SBD",
        currencyName: "Solomon Islands Dollar",
        currencySymbol: "$",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX XXXX",
        usesPostalCode: false,
      }),
      // somalie
      new Country({
        name: "Somalia",
        officialName: "Federal Republic of Somalia",
        slug: "somalia",
        iso2: "SO",
        iso3: "SOM",
        numericCode: "706",
        countryCode: "252",
        currencyCode: "SOS",
        currencyName: "Somali Shilling",
        currencySymbol: "S",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "South Africa",
        officialName: "Republic of South Africa",
        slug: "south-africa",
        iso2: "ZA",
        iso3: "ZAF",
        numericCode: "710",
        countryCode: "27",
        currencyCode: "ZAR",
        currencyName: "South African Rand",
        currencySymbol: "R",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "South Sudan",
        officialName: "Republic of South Sudan",
        slug: "south-sudan",
        iso2: "SS",
        iso3: "SSD",
        numericCode: "728",
        countryCode: "211",
        currencyCode: "SSP",
        currencyName: "South Sudanese Pound",
        currencySymbol: "£",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Spain",
        officialName: "Kingdom of Spain",
        slug: "spain",
        iso2: "ES",
        iso3: "ESP",
        numericCode: "724",
        countryCode: "34",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Sri Lanka",
        officialName: "Democratic Socialist Republic of Sri Lanka",
        slug: "sri-lanka",
        iso2: "LK",
        iso3: "LKA",
        numericCode: "144",
        countryCode: "94",
        currencyCode: "LKR",
        currencyName: "Sri Lankan Rupee",
        currencySymbol: "Rs",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Sudan",
        officialName: "Republic of the Sudan",
        slug: "sudan",
        iso2: "SD",
        iso3: "SDN",
        numericCode: "729",
        countryCode: "249",
        currencyCode: "SDG",
        currencyName: "Sudanese Pound",
        currencySymbol: "ج.س.",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Suriname",
        officialName: "Republic of Suriname",
        slug: "suriname",
        iso2: "SR",
        iso3: "SUR",
        numericCode: "740",
        countryCode: "597",
        currencyCode: "SRD",
        currencyName: "Surinamese Dollar",
        currencySymbol: "$",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX-XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Sweden",
        officialName: "Kingdom of Sweden",
        slug: "sweden",
        iso2: "SE",
        iso3: "SWE",
        numericCode: "752",
        countryCode: "46",
        currencyCode: "SEK",
        currencyName: "Swedish Krona",
        currencySymbol: "kr",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX-XXX XX XX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Switzerland",
        officialName: "Swiss Confederation",
        slug: "switzerland",
        iso2: "CH",
        iso3: "CHE",
        numericCode: "756",
        countryCode: "41",
        currencyCode: "CHF",
        currencyName: "Swiss Franc",
        currencySymbol: "CHF",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XX XX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Syria",
        officialName: "Syrian Arab Republic",
        slug: "syria",
        iso2: "SY",
        iso3: "SYR",
        numericCode: "760",
        countryCode: "963",
        currencyCode: "SYP",
        currencyName: "Syrian Pound",
        currencySymbol: "£S",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Taiwan",
        officialName: "Taiwan",
        slug: "taiwan",
        iso2: "TW",
        iso3: "TWN",
        numericCode: "158",
        countryCode: "886",
        currencyCode: "TWD",
        currencyName: "New Taiwan Dollar",
        currencySymbol: "NT$",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Tajikistan",
        officialName: "Republic of Tajikistan",
        slug: "tajikistan",
        iso2: "TJ",
        iso3: "TJK",
        numericCode: "762",
        countryCode: "992",
        currencyCode: "TJS",
        currencyName: "Tajikistani Somoni",
        currencySymbol: "ЅМ",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Tanzania",
        officialName: "United Republic of Tanzania",
        slug: "tanzania",
        iso2: "TZ",
        iso3: "TZA",
        numericCode: "834",
        countryCode: "255",
        currencyCode: "TZS",
        currencyName: "Tanzanian Shilling",
        currencySymbol: "TSh",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Thailand",
        officialName: "Kingdom of Thailand",
        slug: "thailand",
        iso2: "TH",
        iso3: "THA",
        numericCode: "764",
        countryCode: "66",
        currencyCode: "THB",
        currencyName: "Thai Baht",
        currencySymbol: "฿",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Timor-Leste",
        officialName: "Democratic Republic of Timor-Leste",
        slug: "timor-leste",
        iso2: "TL",
        iso3: "TLS",
        numericCode: "626",
        countryCode: "670",
        currencyCode: "USD",
        currencyName: "US Dollar",
        currencySymbol: "$",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Togo",
        officialName: "Togolese Republic",
        slug: "togo",
        iso2: "TG",
        iso3: "TGO",
        numericCode: "768",
        countryCode: "228",
        currencyCode: "XOF",
        currencyName: "West African CFA Franc",
        currencySymbol: "CFA",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XX XX XX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Tonga",
        officialName: "Kingdom of Tonga",
        slug: "tonga",
        iso2: "TO",
        iso3: "TON",
        numericCode: "776",
        countryCode: "676",
        currencyCode: "TOP",
        currencyName: "Tongan Paʻanga",
        currencySymbol: "T$",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Trinidad and Tobago",
        officialName: "Republic of Trinidad and Tobago",
        slug: "trinidad-and-tobago",
        iso2: "TT",
        iso3: "TTO",
        numericCode: "780",
        countryCode: "1868",
        currencyCode: "TTD",
        currencyName: "Trinidad and Tobago Dollar",
        currencySymbol: "TT$",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "(XXX) XXX-XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Tunisia",
        officialName: "Republic of Tunisia",
        slug: "tunisia",
        iso2: "TN",
        iso3: "TUN",
        numericCode: "788",
        countryCode: "216",
        currencyCode: "TND",
        currencyName: "Tunisian Dinar",
        currencySymbol: "د.ت",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Turkey",
        officialName: "Republic of Turkey",
        slug: "turkey",
        iso2: "TR",
        iso3: "TUR",
        numericCode: "792",
        countryCode: "90",
        currencyCode: "TRY",
        currencyName: "Turkish Lira",
        currencySymbol: "₺",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Turkmenistan",
        officialName: "Turkmenistan",
        slug: "turkmenistan",
        iso2: "TM",
        iso3: "TKM",
        numericCode: "795",
        countryCode: "993",
        currencyCode: "TMT",
        currencyName: "Turkmenistan Manat",
        currencySymbol: "m",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XX XXXXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Tuvalu",
        officialName: "Tuvalu",
        slug: "tuvalu",
        iso2: "TV",
        iso3: "TUV",
        numericCode: "798",
        countryCode: "688",
        currencyCode: "AUD",
        currencyName: "Australian Dollar",
        currencySymbol: "$",
        minLengthPhone: 6,
        maxLengthPhone: 6,
        phoneFormat: "XXX XXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Uganda",
        officialName: "Republic of Uganda",
        slug: "uganda",
        iso2: "UG",
        iso3: "UGA",
        numericCode: "800",
        countryCode: "256",
        currencyCode: "UGX",
        currencyName: "Ugandan Shilling",
        currencySymbol: "USh",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Ukraine",
        officialName: "Ukraine",
        slug: "ukraine",
        iso2: "UA",
        iso3: "UKR",
        numericCode: "804",
        countryCode: "380",
        currencyCode: "UAH",
        currencyName: "Ukrainian Hryvnia",
        currencySymbol: "₴",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XX XX",
        usesPostalCode: true,
      }),
      new Country({
        name: "United Arab Emirates",
        officialName: "United Arab Emirates",
        slug: "united-arab-emirates",
        iso2: "AE",
        iso3: "ARE",
        numericCode: "784",
        countryCode: "971",
        currencyCode: "AED",
        currencyName: "UAE Dirham",
        currencySymbol: "د.إ",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "United Kingdom",
        officialName: "United Kingdom of Great Britain and Northern Ireland",
        slug: "united-kingdom",
        iso2: "GB",
        iso3: "GBR",
        numericCode: "826",
        countryCode: "44",
        currencyCode: "GBP",
        currencyName: "British Pound Sterling",
        currencySymbol: "£",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXXX XXX XXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "United States",
        officialName: "United States of America",
        slug: "united-states",
        iso2: "US",
        iso3: "USA",
        numericCode: "840",
        countryCode: "1",
        currencyCode: "USD",
        currencyName: "US Dollar",
        currencySymbol: "$",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "(XXX) XXX-XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Uruguay",
        officialName: "Oriental Republic of Uruguay",
        slug: "uruguay",
        iso2: "UY",
        iso3: "URY",
        numericCode: "858",
        countryCode: "598",
        currencyCode: "UYU",
        currencyName: "Uruguayan Peso",
        currencySymbol: "$U",
        minLengthPhone: 8,
        maxLengthPhone: 8,
        phoneFormat: "XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Uzbekistan",
        officialName: "Republic of Uzbekistan",
        slug: "uzbekistan",
        iso2: "UZ",
        iso3: "UZB",
        numericCode: "860",
        countryCode: "998",
        currencyCode: "UZS",
        currencyName: "Uzbekistani Som",
        currencySymbol: "so'm",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XX XX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Vanuatu",
        officialName: "Republic of Vanuatu",
        slug: "vanuatu",
        iso2: "VU",
        iso3: "VUT",
        numericCode: "548",
        countryCode: "678",
        currencyCode: "VUV",
        currencyName: "Vanuatu Vatu",
        currencySymbol: "Vt",
        minLengthPhone: 7,
        maxLengthPhone: 7,
        phoneFormat: "XXX XXXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Vatican City",
        officialName: "Vatican City State",
        slug: "vatican-city",
        iso2: "VA",
        iso3: "VAT",
        numericCode: "336",
        countryCode: "379",
        currencyCode: "EUR",
        currencyName: "Euro",
        currencySymbol: "€",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XX XXXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Venezuela",
        officialName: "Bolivarian Republic of Venezuela",
        slug: "venezuela",
        iso2: "VE",
        iso3: "VEN",
        numericCode: "862",
        countryCode: "58",
        currencyCode: "VES",
        currencyName: "Venezuelan Bolívar",
        currencySymbol: "Bs.S",
        minLengthPhone: 10,
        maxLengthPhone: 10,
        phoneFormat: "XXX-XXX-XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Vietnam",
        officialName: "Socialist Republic of Vietnam",
        slug: "vietnam",
        iso2: "VN",
        iso3: "VNM",
        numericCode: "704",
        countryCode: "84",
        currencyCode: "VND",
        currencyName: "Vietnamese Dong",
        currencySymbol: "₫",
        minLengthPhone: 9,
        maxLengthPhone: 10,
        phoneFormat: "XXX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Yemen",
        officialName: "Republic of Yemen",
        slug: "yemen",
        iso2: "YE",
        iso3: "YEM",
        numericCode: "887",
        countryCode: "967",
        currencyCode: "YER",
        currencyName: "Yemeni Rial",
        currencySymbol: "﷼",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XXX XXX XXX",
        usesPostalCode: false,
      }),
      new Country({
        name: "Zambia",
        officialName: "Republic of Zambia",
        slug: "zambia",
        iso2: "ZM",
        iso3: "ZMB",
        numericCode: "894",
        countryCode: "260",
        currencyCode: "ZMW",
        currencyName: "Zambian Kwacha",
        currencySymbol: "ZK",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: true,
      }),
      new Country({
        name: "Zimbabwe",
        officialName: "Republic of Zimbabwe",
        slug: "zimbabwe",
        iso2: "ZW",
        iso3: "ZWE",
        numericCode: "716",
        countryCode: "263",
        currencyCode: "ZWL",
        currencyName: "Zimbabwean Dollar",
        currencySymbol: "$",
        minLengthPhone: 9,
        maxLengthPhone: 9,
        phoneFormat: "XX XXX XXXX",
        usesPostalCode: false,
      }),
    ];
  }
  